"""Testing migrations

Revision ID: 5b973380dc0a
Revises: 
Create Date: 2017-11-14 02:58:08.365838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b973380dc0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TestTable',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('TestColumn', sa.String(), nullable=True),
    sa.Column('Created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TestTable')
    # ### end Alembic commands ###
