"""Adding new table and a column to the first one

Revision ID: 5bfb2527602d
Revises: 5b973380dc0a
Create Date: 2017-11-14 03:05:13.251994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bfb2527602d'
down_revision = '5b973380dc0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AnotherTestTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Words', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('TestTable', sa.Column('AddedColumn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TestTable', 'AddedColumn')
    op.drop_table('AnotherTestTable')
    # ### end Alembic commands ###
