"""move models file

Revision ID: 8e1d6ad70b6e
Revises: ffdd0cf544c4
Create Date: 2017-11-14 12:22:29.239149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1d6ad70b6e'
down_revision = 'ffdd0cf544c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TableThree',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.add_column('AnotherTestTable', sa.Column('Id', sa.Integer(), nullable=False))
    op.drop_column('AnotherTestTable', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AnotherTestTable', sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"AnotherTestTable_id_seq"\'::regclass)'), nullable=False))
    op.drop_column('AnotherTestTable', 'Id')
    op.drop_table('TableThree')
    # ### end Alembic commands ###
